from pathlib import Path

TARGET = Path("android/app/src/main/java/com/betterdeepseek/app/MainActivity.kt")
src = TARGET.read_text(encoding="utf-8")
original = src

# 1. Imports
old_imports = '''import android.annotation.SuppressLint
import android.app.Activity
import android.content.Intent
import android.content.res.Configuration
import android.graphics.Color
import android.net.Uri
import android.os.Bundle
import android.util.Log
import android.view.View
import android.view.ViewGroup
import android.webkit.CookieManager
import android.webkit.ValueCallback
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import android.webkit.MimeTypeMap
import androidx.activity.ComponentActivity
import androidx.activity.OnBackPressedCallback
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import android.widget.FrameLayout
import androidx.core.view.ViewCompat
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.webkit.WebViewAssetLoader
import java.io.ByteArrayInputStream
import java.util.concurrent.TimeUnit
import okhttp3.OkHttpClient
import okhttp3.Request'''

new_imports = '''import android.annotation.SuppressLint
import android.app.Activity
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Intent
import android.content.IntentFilter
import android.content.res.Configuration
import android.graphics.Color
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.util.Log
import android.view.View
import android.view.ViewGroup
import android.webkit.CookieManager
import android.webkit.ValueCallback
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import android.webkit.MimeTypeMap
import androidx.activity.ComponentActivity
import androidx.activity.OnBackPressedCallback
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import android.widget.FrameLayout
import androidx.core.content.ContextCompat
import androidx.core.view.ViewCompat
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.webkit.WebViewAssetLoader
import java.io.ByteArrayInputStream
import java.util.concurrent.TimeUnit
import okhttp3.OkHttpClient
import okhttp3.Request'''

if old_imports not in src:
    raise SystemExit("imports anchor not found")
src = src.replace(old_imports, new_imports, 1)

# 2. Termux receiver registry field
old_fields = '''    @Volatile private var pendingPickFilesRequestId: String? = null
    @Volatile private var pendingPickFilesMode: String? = null'''
new_fields = '''    @Volatile private var pendingPickFilesRequestId: String? = null
    @Volatile private var pendingPickFilesMode: String? = null

    // Termux RUN_COMMAND: per-request BroadcastReceiver registry. Key is the
    // requestId generated by WebViewBridge.handleRunTermuxCommand.
    private val termuxReceivers = java.util.Collections.synchronizedMap(
        mutableMapOf<String, BroadcastReceiver>()
    )
    private val TERMUX_TIMEOUT_MS = 5L * 60 * 1000'''
if old_fields not in src:
    raise SystemExit("fields anchor not found")
src = src.replace(old_fields, new_fields, 1)

# 3. Wire bridge.onRunTermux after onPickFiles block
old_wiring = '''        assetLoader =
                WebViewAssetLoader.Builder()'''
new_wiring = '''        bridge.onRunTermux = { requestId, command, args, workdir ->
            runOnUiThread {
                try {
                    launchTermuxCommand(requestId, command, args, workdir)
                } catch (t: Throwable) {
                    Log.e(TAG, "Termux launch failed", t)
                    bridge.deliverTermuxResult(
                        requestId,
                        ok = false,
                        stdout = "",
                        stderr = "",
                        exitCode = null,
                        error = "Failed to launch Termux: ${t.message ?: t.javaClass.simpleName}"
                    )
                }
            }
        }

        assetLoader =
                WebViewAssetLoader.Builder()'''
if old_wiring not in src:
    raise SystemExit("wiring anchor not found")
src = src.replace(old_wiring, new_wiring, 1)

# 4. onDestroy cleanup
old_destroy = '''    override fun onDestroy() {
        bridge.onThemeChanged = null
        bridge.evaluateJs = null
        bridge.onPickFiles = null
        webView.removeJavascriptInterface(BRIDGE_NAME)'''
new_destroy = '''    override fun onDestroy() {
        bridge.onThemeChanged = null
        bridge.evaluateJs = null
        bridge.onPickFiles = null
        bridge.onRunTermux = null
        synchronized(termuxReceivers) {
            termuxReceivers.values.forEach { runCatching { unregisterReceiver(it) } }
            termuxReceivers.clear()
        }
        webView.removeJavascriptInterface(BRIDGE_NAME)'''
if old_destroy not in src:
    raise SystemExit("onDestroy anchor not found")
src = src.replace(old_destroy, new_destroy, 1)

# 5. launchTermuxCommand function, before companion object
old_companion = '''    companion object {
        private const val BRIDGE_NAME = "AndroidBridge"'''
new_companion = '''    // -- Termux RUN_COMMAND --------------------------------------------

    /**
     * Launch the Termux:API RunCommandService for the given requestId and
     * register a one-shot BroadcastReceiver to capture the result via the
     * PendingIntent broadcast. Bare command names are resolved against the
     * standard Termux binary path; absolute paths are used as-is.
     */
    private fun launchTermuxCommand(
        requestId: String,
        command: String,
        args: List<String>,
        workdir: String?
    ) {
        val action = "com.betterdeepseek.app.TERMUX_RESULT.$requestId"

        val commandPath = if (command.startsWith("/")) {
            command
        } else {
            "/data/data/com.termux/files/usr/bin/$command"
        }

        val receiver = object : BroadcastReceiver() {
            override fun onReceive(ctx: android.content.Context?, intent: Intent?) {
                runCatching { unregisterReceiver(this) }
                synchronized(termuxReceivers) { termuxReceivers.remove(requestId) }

                val stdout = intent?.getStringExtra("com.termux.api.extra.STDOUT") ?: ""
                val stderr = intent?.getStringExtra("com.termux.api.extra.STDERR") ?: ""
                val exitCode = intent?.getIntExtra("com.termux.api.extra.EXIT_CODE", -1)
                val err = intent?.getIntExtra("com.termux.api.extra.ERR", 0) ?: 0
                val errmsg = intent?.getStringExtra("com.termux.api.extra.ERRMSG")

                if (err != 0 || !errmsg.isNullOrBlank()) {
                    bridge.deliverTermuxResult(
                        requestId, ok = false, stdout = stdout, stderr = stderr,
                        exitCode = null,
                        error = errmsg?.takeIf { it.isNotBlank() } ?: "Termux:API error code $err"
                    )
                } else {
                    bridge.deliverTermuxResult(
                        requestId, ok = true, stdout = stdout, stderr = stderr,
                        exitCode = exitCode, error = null
                    )
                }
            }
        }

        val filter = IntentFilter(action)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            ContextCompat.registerReceiver(this, receiver, filter, ContextCompat.RECEIVER_NOT_EXPORTED)
        } else {
            @Suppress("DEPRECATION")
            registerReceiver(receiver, filter)
        }
        synchronized(termuxReceivers) { termuxReceivers[requestId] = receiver }

        val resultIntent = Intent(action).apply { setPackage(packageName) }
        val pendingIntent = PendingIntent.getBroadcast(
            this, 0, resultIntent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )

        val runIntent = Intent("com.termux.RUN_COMMAND").apply {
            setClassName("com.termux.api", "com.termux.api.app.RunCommandService")
            putExtra("com.termux.api.extra.COMMAND_PATH", commandPath)
            if (args.isNotEmpty()) {
                putExtra("com.termux.api.extra.ARGUMENTS", args.toTypedArray())
            }
            if (workdir != null) putExtra("com.termux.api.extra.WORKDIR", workdir)
            putExtra("com.termux.api.extra.COMMAND_LABEL", "BDS: $command")
            putExtra("com.termux.api.extra.COMMAND_DESCRIPTION", "Better DeepSeek /termux")
            putExtra("com.termux.api.extra.PENDING_INTENT", pendingIntent)
        }

        startService(runIntent)

        webView.postDelayed({
            val stillPending = synchronized(termuxReceivers) { termuxReceivers.remove(requestId) }
            if (stillPending != null) {
                runCatching { unregisterReceiver(stillPending) }
                bridge.deliverTermuxResult(
                    requestId, ok = false, stdout = "", stderr = "", exitCode = null,
                    error = "Termux command timed out after 5 minutes. " +
                        "If this is unexpected, ensure `allow-external-apps=true` " +
                        "is set in `~/.termux/termux.properties` inside Termux " +
                        "(then fully restart Termux)."
                )
            }
        }, TERMUX_TIMEOUT_MS)
    }

    companion object {
        private const val BRIDGE_NAME = "AndroidBridge"'''
if old_companion not in src:
    raise SystemExit("companion object anchor not found")
src = src.replace(old_companion, new_companion, 1)

if src == original:
    raise SystemExit("no changes made")

TARGET.write_text(src, encoding="utf-8")
print("Patched MainActivity.kt for Termux integration")
